spring:
  rabbitmq:
    host: 188.131.253.61
    port: 5672
    username: se
    password: se123456

  cloud:
    bus:
      enabled: true
      trace:
        enabled: true

  datasource:
    url: jdbc:mysql://188.131.253.61:3306/se
    username: se
    password: se123456!@#
    driver-class-name: com.mysql.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

app:
  version: @project.version@


