spring:
  rabbitmq:
    host: 188.131.253.61
    port: 5672
    username: se
    password: se123456

  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

app:
  version: @project.version@
